spring:
  profiles:
    active: eureka1


#客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6061/eureka/,http://127.0.0.1:6062/eureka/

---
spring:
  profiles: eureka1
  application:
    name: ad-eureka-server1

server:
  port: 6061


---
spring:
  profiles: eureka2
  application:
    name: ad-eureka-server2

server:
  port: 6062